import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import nj from "numjs"
import React, { useState } from 'react';
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

    //var a= nj.cos(3.14);
function Header({title }) {
    return <h1>{title ? title : 'Default title'}</h1>;
  }
  

  var RI   = nj.concatenate(nj.ones([10,1]), nj.zeros([10,1]))
  //Fourrier transformation
  var fft  = nj.fft(RI)
  //Fourrier inverse transformation
  var ifft = nj.ifft(fft);
  //Convolution product
  var c= nj.convolve(RI, [[ 1, 2, 1], [ 0, 0, 0], [-1,-2,-1]])

  function Matrix({ matrix }) {
    return (
      <table>
        <tbody>
          {matrix.tolist().map((row, i) => (
            <tr key={i}>
              {row.map((col, j) => (
                <td key={j}>{col}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    );
  }
 

    function Example() {
      const [count, setCount] = useState(0);
  
    return (
        <div>
          <p>You clicked {count} times</p>
          <button onClick={() => setCount(count + 1)}>
          <Link href="/"/>

         
         </button>
       </div>
     );
   }
 
export default function Ft() {
  const [showMult, setShowMult] = useState(false);

  return (
    <>
      <Head>
        <title>FFT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header title="Fourrier Fast Transformation"/>
        

     

    <button onClick={() => setShowMult(!showMult)}>
        Multiply
      </button>
      {showMult && <Matrix matrix={matrix3} />}
    <Example />
    <Matrix matrix={RI} />

    
    
        
      </main>
    </>
  )
}
