import Head from 'next/head'
import { Inter } from '@next/font/google'
import Image from 'next/image'
import Layout from '../components/Layout.js'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <Head>
      <title>ALGEBRA</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
        
    <main className={styles.main}>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/maths.jpg"
            alt="Algebra Logo"
            width={180}
            height={37}
            priority />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="calcul"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Matrix Calculations
            </h2>
            <p className={inter.className}>
              Do your matrix calculations with simplicity !
            </p>
          </a>

          <a
            href="fourriertransf"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              FFT
            </h2>
            <p className={inter.className}>
              Discorver Fourrier Transformations and enjoy.
            </p>
          </a>

          <a
            href="sc"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Scientific operations
            </h2>
            <p className={inter.className}>
              Do your calculations with your own!
            </p>
          </a>

          <a
            href="https://www.bibmath.net/ressources/index.php?action=affiche&quoi=mathspe/cours/alglin.html"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn
            </h2>
            <p className={inter.className}>
              Learn about algebra with a fun, interactive way !
            </p>
          </a>
        </div>
        </main>
      </>
     
  )
}
