import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import React, { useState } from 'react';
import ScientificCalculator from '../components/ScientificCalculator';



const inter = Inter({ subsets: ['latin'] })
 
export default function Sc() {
  return (
    <>
      <Head>
       <title>Scientific calculus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <title>Scientific calculus</title>

      <main className={styles.main}>
        <ScientificCalculator />
      </main>
    </>
  )
}
