import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import nj from "numjs"
import React, { useState } from 'react';
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

var a= nj.cos(3.14);
var c=nj.arccos();
var c=nj.arcsin();
var e=nj.sin();
function Header({title }) {
    return <h1>{title ? title : 'Default title'}</h1>;
  }
  

  
 

    function Example() {
      const [count, setCount] = useState(0);
  
    return (
        <div>
          <p>You clicked {count} times</p>
          <button onClick={() => setCount(count + 1)}>

         
         </button>
       </div>
     );
   }
 
export default function Sc() {
  const [showMult, setShowMult] = useState(false);
  const [val,setVal]=useState(0.0);
  const handleChange = (e) => {
    var newVal = val;
    newVal = Number(e.target.value);
    setVal(newVal);
    console.log(nj.cos(val));

  };

  return (
    <>
      <Head>
        <title>Scientific calculus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header title="Scientific calculus"/>
      
      

        <br/>
        <input
              type="number"
              onChange={(e) => handleChange(e)}
            />
    
        
      </main>
    </>
  )
}
